name: Build APK

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.ref }}

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.18.0'

      - name: Install dependencies
        run: npm install

      - name: Build APK
        run: |
          cd android
          ./gradlew assembleRelease
        env:
          ANDROID_HOME: ${{ secrets.ANDROID_HOME }}
          JAVA_HOME: ${{ secrets.JAVA_HOME }}

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: android/app/build/outputs/apk/release/app-release.apk
